### ISSUE TITLE
更智能的课表

### ISSUE THREAD

**Issue by yhshu** [weNEU/weNEU#1]
在今日课程全部结束之后，可否显示明日课程呢？

**Comment by RavenLite** [comment]
很好的建议！我们将在1.2版本加入这一特性！

**Comment by RavenLite** [comment]
weNEU 1.2版本已经上线啦。我们加入了指向明日课表的按钮。暂时未想到更好的解决方案。（有考虑过根据时间来判断，但是有同学提议有时还需要看一下今天上什么课了。如果像方圆那样显示的话感觉整个卡片又有些过长）
